name: Build and Export Next.js
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Clean up docs directory
        run: rm -rf docs

      - name: Rename output directory
        run: mv out docs

      - name: Commit and push to main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "ci: update github pages (automated commit)"
          git push
